include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

test:1.4:
  extends:
    - .julia:1.4
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:latest

test:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  allow_failure: true

# https://github.com/JuliaGPU/gitlab-ci
