language: julia

os:
  - linux
julia:
  - 1.3
  - 1.5
  - nightly
env:
  - JULIA_NUM_THREADS=1
  - JULIA_NUM_THREADS=6

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly

cache:
  directories:
  - $HOME/.julia/artifacts
